// FileSenderClient/src/app/components/file-download/file-download.component.ts
import { Component, ElementRef, OnInit, ViewChild } from '@angular/core';
import { ActivatedRoute, ActivatedRouteSnapshot } from '@angular/router';
import { FileService } from 'src/app/shared/services/file.service';
import { FileDownloadModel } from 'src/app/shared/services/models/fileDownloadModel';
import { FileModel } from 'src/app/shared/services/models/fileModel';


@Component({
  selector: 'app-file-download',
  templateUrl: './file-download.component.html',
  styleUrls: ['./file-download.component.scss']
})
export class FileDownloadComponent implements OnInit {


  files!: FileDownloadModel[];
  displayedColumns: string[] = ['fileName', 'option'];
  constructor(private fileService: FileService, private route: ActivatedRoute) { }


  generateLink(response: any, filename: string): void {
    let dataType = response.type;
    let binaryData = [];
    binaryData.push(response);
    let downloadLink = document.createElement('a');
    downloadLink.href = window.URL.createObjectURL(new Blob(binaryData, {type: dataType}));
    if (filename)
          downloadLink.setAttribute('download', filename);
          document.body.appendChild(downloadLink);
          downloadLink.click();
  }

  downloadFile(id: string, filename: string) {
    this.fileService.downloadSingleFile(id).subscribe(response => {
      // const blob = new Blob([resp], {type: 'application/pdf'});
      // const url = window.URL.createObjectURL(blob);
      // window.open(url);
      this.generateLink(response, filename);
      
    })
  }

  downloadAll() {
    let guid = this.route.snapshot.paramMap.get('guid')!;
    this.fileService.downloadAllFiles(guid).subscribe(response => {
      this.generateLink(response, "archive.zip");
    })
  }

  ngOnInit(): void {
    this.route.data.subscribe(resp => {
      this.files = resp['files'];
    })
  }

}

<div class="flex-wrap">
    <table style="width: 100%;" mat-table [dataSource]="files" class="mat-elevation-z8">
        <ng-container matColumnDef="fileName">
          <th mat-header-cell *matHeaderCellDef> File name</th>
          <td mat-cell *matCellDef="let element"> {{element.fileName}} </td>
        </ng-container>
        <ng-container matColumnDef="option">
          <th mat-header-cell *matHeaderCellDef> Action </th>
          <td  mat-cell *matCellDef="let element">
            <a  (click)="downloadFile(element.fileId, element.fileName)" mat-flat-button color="primary">Download</a>
          </td>
        </ng-container>      
        <tr mat-header-row *matHeaderRowDef="displayedColumns"></tr>
        <tr mat-row *matRowDef="let row; columns: displayedColumns;"></tr>
      </table>
      <button (click)="downloadAll()" mat-flat-button color="accent">Download All</button>
</div>

// file-sender-vue/src/views/fileDownload.vue

<script setup lang="ts">
import { AxiosKey } from '@/shared/httpClient/symbo';
import { ref } from '@vue/reactivity';
import { onMounted } from '@vue/runtime-core';
import { inject, Ref } from 'vue';
import { useRoute } from 'vue-router';
import { FileDownloadModel } from '../shared/models/fileDownloadModel'

const http = inject(AxiosKey)!;
const files: Ref<FileDownloadModel[]> = ref([]);
const route = useRoute();

onMounted(async () => {
    let resp = await http.listAll(route.params.guid as string);
    files.value = resp.data;

})

const generateLink = (response: any, filename: string): void  => {
    let dataType = response.type;
    let binaryData = [];
    binaryData.push(response);
    let downloadLink = document.createElement('a');
    downloadLink.href = window.URL.createObjectURL(new Blob(binaryData, {type: dataType}));
    if (filename)
          downloadLink.setAttribute('download', filename);
          document.body.appendChild(downloadLink);
          downloadLink.click();
  }

const downloadSingle = async (id: string, filename: string) => {
   let resp = await http.downloadSingleFile(id);
   generateLink(resp.data, filename);

}
</script>

<template>
    <h1>Hello</h1>
    <table>
            <thead>
                <tr>
                    <th>File name</th>
                    <th>Options</th>
                </tr>
            </thead>
            <tbody>
                <tr v-for="file in files" :key="file.fileId">
                    <td>{{file.fileName}}</td>
                    <td><button @click="downloadSingle(file.fileId, file.fileName)">Download</button></td>
                </tr>
            </tbody>
        </table>
</template>


<style lang="scss">

</style>
